### ISSUE TITLE
ESS群规 | ScapegoatTree的小窝

### ISSUE THREAD

**Issue by ScapegoatTree316** [ScapegoatTree316/Comment#3]
https://scapegoattree316.github.io/2021/05/21/ESS%E7%BE%A4%E8%A7%84/

**Comment by ScapegoatTree316** [comment]
欢迎评论

**Comment by doflake** [comment]
**ESS 管理前来报告 [doge]**

**Comment by ScapegoatTree316** [comment]
1.请规定绯闻的范围
2.请规定辱骂的范围
3.请规定上课的范围
4.请规定考试的范围
5.请规定斗图的范围（如鸽子经常发的表情包算不算？）
6.请规定恶意解答的范围
7.请规定广告的范围（“鸽子很可爱，请你来撸”算广告吗？）
8.书面检讨的形式是什么？
9.管理员（群主）违纪谁来制裁（重点！）
10.请管理员（群主）以人格担保投票表决及投诉的民主性、公正性

REPLY：
1、我以人格担保投票表决及投诉的民主性、公正性
2、1,2,3,4,5,6,7主观判断。
3、鸽子经常发的表情包不算
4、“鸽子很可爱，请你来撸”不算广告吗
5、个人解除惩罚的途径是提交书面检讨，视情况轻重程度要求300-1600字不等，内容包含:   事情的起因和经过，造成的不良影响，今后的改进措施
  【拍照或者扫描或电子】私信发送到管理员（群主）QQ
6、根据第1点

**Comment by ScapegoatTree316** [comment]
标点符号已改正
